//window class
#define	NOTES_PROG_MAIN_CLASS	L"__$$$__agNotesMainClass__$$$__"
#define	NOTES_OWNER_CLASS		L"__$$$__agNotesOwnerClass__$$$__"
#define NWC_SKINNABLE_CLASS		L"__$$$__agNoteSkinnableClass__$$$__"
#define	NWC_GRIP_CLASS			L"__$$$__agNoteGripClass__$$$__"
#define	NWC_TBR_BUTTON_CLASS	L"__$$$__agNoteTbrButtonClass__$$$__"
#define	NWC_TOOLBAR_CLASS		L"__$$$__agNoteToolbarClass__$$$__"
#define	NWC_NOTE_MARK_CLASS		L"__$$$__agNoteMarkClass__$$$__"

#define	PROG_NAME				L"PNotes"
#define	PROG_EXE_NAME			"PNotes.exe"
#define	PROG_EXE_NAME_W			L"PNotes.exe"
#define	GROUP_IMAGES_FILE		L"\\groups.images"
#define	ICONS_FILE				L"\\pnotes.resources"
#define	DICT_FILE				L"dictionaries.txt"

//shortcut strings
#define	LINK_NAME				"\\PNotes.lnk"

//note window properties
#define PH_EDIT					L"Edit"
#define	PH_GRIP					L"Grip"
#define	PH_STATIC				L"Static"
#define	PH_COMMANDS				L"TbrCommands"
#define PH_DELHIDE				L"TbrDelHide"
#define PH_BELL					L"BellWindow"

//ini files sections and keys
#define	S_FILE					L"file"
#define	S_NOTE					L"note"
#define	S_SETTINGS				L"settings"
#define	S_APPEARANCE			L"appearance"
#define	S_ADD_APPEARANE			L"add_appearance"
#define	S_NOTE_CREATION			L"creation"
#define	S_DOCKING				L"docking"
#define	S_DIARY					L"diary"
#define S_SKIN					L"skin"
#define S_FONT					L"font"
#define	S_MESSAGES				L"messages"
#define	S_CAPTION_FONT			L"cfont"
#define	S_COLOR					L"color"
#define S_CAPTION_COLOR			L"ccapcolor"
#define	S_BCKG_COLOR			L"bckgcolor"
#define	S_OPTIONS				L"options"
#define	S_COLUMNS				L"columns"
#define	S_TABS					L"tabs"			
#define	S_TEXT					L"text"
#define	S_POSITION				L"position"
#define	S_SCHEDULE				L"schedule"
#define	S_DATA					L"data"
#define	S_MENU					L"menu"
#define	S_FORMAT				L"format"
#define	S_SOUND					L"sound"
#define	S_HOTKEYS				L"hotkeys"
#define	S_NOTE_HOTKEYS			L"note_hotkeys"
#define	S_EDIT_HOTKEYS			L"edit_hotkeys"
#define	S_PRE_TAGS				L"tags_pre"
#define	S_COMMANDS				L"commands"
#define	S_EXITFLAG				L"exitflag"
#define	S_DEFSIZE				L"defsize"
#define	S_PREVIEW				L"preview"
#define	S_GROUPS				L"groups"
#define	S_CAPTIONS				L"captions"
#define	S_STATUS				L"status"
#define	S_CP_DATA				L"cp_data"
#define	S_SEARCH				L"search"
#define	S_SEARCH_HIST			L"search_history"
#define	S_REPLACE_HIST			L"replace_history"
#define	S_DATE_FORMAT_CHARS		L"date_format_chars"
#define	S_TIME_FORMAT_CHARS_H12	L"time_format_chars_h12"
#define	S_TIME_FORMAT_CHARS_H24	L"time_format_chars_h24"
#define	S_TIME_FORMAT_CHARS		L"time_format_chars"
#define	S_LEFT_PANEL			L"left_panel"
#define	S_RESULTS_COLS			L"search_columns"
#define	S_TITLES_COLS			L"titles_columns"
#define	S_FAVORITES				L"favorites"
#define	S_WEEKDAYS				L"weekdays"
#define	S_WEEKDAYS_FULL			L"weekdays_full"
#define	S_ORDINALS				L"ordinals"
#define	S_LOGIN_CAPTIONS		L"login_captions"
#define	S_SEARCH_ENG_COLUMNS	L"engines_columns"
#define	S_SEARCH_ENGINES		L"search_engines"
#define	S_EXT_PROGS_COLUMNS		L"ext_progs_columns"
#define	S_EXTERNAL_PROGRAMS		L"external_programs"
#define	S_DEF_SAVE_NAME			L"def_naming"
#define	S_SEND_RECEIVE_STATUS	L"send_rec"
#define	S_CONTACTS				L"contacts"
#define	S_CONTACTS_COLUMNS		L"contacts_columns"
#define	S_SEARCH_DATES_FIELDS	L"search_dates_fields"
#define	S_WINDOWS_COLUMNS		L"windows_columns"
#define	S_CONT_GROUPS			L"cont_groups"
#define	S_LOCAL_SYNC_COLUMNS	L"local_sync_columns"
#define	S_LOCAL_SYNCS			L"local_syncs"
#define	S_SPELLING				L"spelling"
#define	S_VOICES				L"voices"
#define	S_STOP_LOOP				L"stop_loop"

#define IK_CP_POSITION			L"cp_position"
#define	IK_CP_LAST_GROUP		L"cp_last_group"
#define	IK_CP_COL_WIDTH			L"cp_col_width"
#define	IK_CP_BU_COL_WIDTH		L"cp_bu_col_width"
#define	IK_CP_COLUMNS_WIDTH		L"cp_columns_width"
#define	IK_CP_SORT_DATA			L"cp_sort_data"
#define	IK_CP_BU_SORT_DATA		L"cp_bu_sort_data"
#define	IK_CP_PVW_VISIBLE		L"cp_pvw_on"
#define	IK_CP_PVW_USE_COLOR		L"cp_pvw_use_color"
#define	IK_CP_PVW_COLOR			L"cp_pvw_color"
#define	IK_CP_ALL_IN_SEARCH		L"cp_all_in_search"
#define	IK_CP_COLS_ORDER		L"cp_cols_order"
#define	IK_CP_ICONS_SIZE		L"cp_icons_size"
#define	IK_RELPOSITION			L"rel_position"
#define	IK_SEARCH_PROMPT		L"quick_search"
#define	IK_SEARCH_RESULTS		L"search_results"
#define	IK_RENAME_CAPTION		L"rename"
#define	IK_PASSWORD				L"pn_data_value"
#define	IK_TIMER_MAIN			L"tmr_main"
#define IK_ENTER_PWRD			L"enter_pwrd"
#define IK_CONF_PWRD			L"conf_pwrd"
#define	IK_OLD_PWRD				L"old_pwrd"
#define	IK_NEW_PWRD				L"new_pwrd"
#define	IK_SMALL_VALUES			L"small_values"
#define	IK_REST_FILTER			L"restore_filter"
#define	IK_REST_CAPTION			L"restore_caption"
#define	IK_LAST_OPTION			L"last_option"
#define	IK_BACKUP_CAPTION		L"backup_caption"
#define	IK_LAST_START_TIME		L"last_start_time"
#define	IK_DF_INDEX				L"df_index"
#define	IK_DIARY_APPEARANCE		L"diary_appearance"
#define	IK_DIARY_LOCK			L"diary_lock"
#define	IK_TOGGLE_SHOW_HIDE		L"show_hide"
#define	IK_TAGS					L"tags"
#define	IK_FAVORITES			L"favorites"
#define	IK_SHOW_MISSING_HELP	L"show_missing_help"
#define	IK_FTP_DATA				L"ftp_data"
#define	IK_VOICE_DEFAULT		L"voice_default"
#define	IK_NEXT_SETTINGS		L"next_settings"
#define	IK_DELETION_TIME		L"deletion"
#define	IK_REAL_DELETION_TIME	L"real_deletion"
#define	IK_LINKS				L"links"
#define	IK_INCOMING				L"incoming"
#define	IK_DEF_SOCKET_PORT		L"def_socket_port"
#define	IK_LOCK					L"lock"
#define	IK_PIN					L"pin"
#define	IK_WINDOWS				L"windows"
#define	IK_SPELL_COLOR			L"spell_color"
#define	IK_SPELL_CULTURE		L"spell_culture"
#define	IK_SPELL_AUTO			L"spell_auto"

//files
#define FN_DATA_FILE			L"notes.pnid"
#define	FN_INI_FILE				L"\\notes.ini"
#define	NOTE_EXTENTION			L".pnote"
#define	BACK_NOTE_EXTENTION		L".pnback"
#define	FULL_BACK_EXTENTION		L"pnfb"
#define TEXT_FILE_EXTENTION		L"txt"

//default control text
#define	DS_CAPTION				L"Preferences"
#define	DS_CAP_SINGLE			L"Current note options"
#define	DS_CTRL_PANEL			L"Control panel"
#define	DS_OK					L"OK"
#define	DS_CANCEL				L"Cancel"
#define	DS_APPLY				L"Apply"
#define	DS_ALERT				L"Alert sound"
#define	DS_SKIN					L"Skin"
#define	DS_PREVIEW				L"Preview"
#define DS_O_COMMON				L"Common notes options"
#define DS_O_FONT				L"The quick brown fox jumps over the lazy dog"
#define	DS_O_DEFAULT			L"Default preferences"
#define	DS_TRANS				L"Allow transparency"
#define	DS_TR_WARNING			L"Value of 100% will result in fully transparent window!"
#define	DS_SHOW_START			L"Show all notes on program start"
#define	DS_SAVE_EXIT			L"Save all on program exit"
#define	DS_SAVE_CONF			L"Confirm saving"
#define DS_CONF_DELETE			L"Confirmation before note deletion"
#define	DS_SHOW_SCROLLBAR		L"Show scrollbar (all notes will be reloaded)"
#define	DS_O_SINGLE				L"Note font"
#define	DS_GROUP_FONT			L"Notes font"
#define DS_ON_STARTUP			L"Run on system startup"
#define	DS_APPEARANCE			L"Appearance"
#define	DS_SCHEDULE				L"Schedule"
#define	DS_TRANSPARENCY			L"Transparency"
#define	DS_MISC					L"Misc"
#define	DS_DEF_SOUND			L"(Default)"
#define	DS_NO_SKIN				L"(No skin)"
#define	DS_GROUP_CAPTION_NEW	L"New group"
#define	DS_GROUP_CAPTION_EDIT	L"Modify group"
#define	DS_CHOOSE_GROUP_ICON	L"Group icon"
#define	DS_CHOOSE_GROUP_NAME	L"Group name"
#define	DS_PICK_ICON			L"Pick an icon for group"
#define	DS_SHOW_GROUP			L"Show all notes from selected group"
#define	DS_HIDE_GROUP			L"Hide all notes from selected group"
#define	DS_ADD_SUBGROUP			L"Add subgroup to selected group"
#define	DS_DELETE_GROUP			L"Delete group"
#define	DS_NOTE_TO_GROUP		L"Add note to selected group"
#define	DS_ADD_TOP_LEVEL_GROUP	L"Add top level group"
#define	DS_GENERAL_GROUP_NAME	L"General"
#define	DS_ALL_NOTES_GROUP		L"All notes"
#define	DS_GROUP				L"Group:"
#define	DS_TOTAL_NOTES			L"Total notes:"
#define	DS_DD_IMPOSSIBLE		L"(drag-and-drop is impossible)"
#define	DS_NOTES_IN_GROUP		L"Notes in group"
#define	DS_NO_CONT_GROUP		L"(None)"

#define	DSK_ALLOW				L"allow"
#define	DSK_SOUND_DEF			L"def_sound"
#define	DSK_SOUND_CUST			L"cust_sound"
#define	DSK_CONF_DELETE			L"confirm_delete"
#define	DSK_CURRENT_STATE		L"current"
#define	DSK_SEARCH_PARAMS		L"params"
#define	DSK_SETTINGS			L"settings"

//datetime format strings
#define	DTS_DATE_FORMAT			L"dd MMM yyyy HH:mm"
#define	DTS_TIME_FORMAT			L"HH:mm"

//mutex - to prevent the program from running twice
#define	NOTES_MUTEX				L"PNotes_Mutex"
#define	UPDATE_CHECK_URL		"pnotes.sourceforge.net"
#define	HOME_PAGE				L"http://pnotes.sf.net"
#define	SKIN_PAGE				L"http://pnotes.sf.net?page=2"
#define	DOWNLOAD_PAGE			L"http://pnotes.sf.net?page=5"
#define	DOWNLOAD_ROOT			L"http://downloads.sourceforge.net/pnotes/"
#define	DOWNLOAD_CHM			L"PNotes.chm"
#define	DOWNLOAD_PDF			L"PNotes.pdf"
#define	HELP_PAGE				L"http://pnotes.sf.net/help/index.html"
#define	PAYPAL_PAGE				L"https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=8YEWS9ZW3VFJS&lc=IL&item_name=PNotes (it is free and will remain free, but your donation wiil definitely help to make it better)&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted"
#define	SPELL_DOWNLOAD			L"http://extensions.openoffice.org/en/dictionaries"
#define	HELP_SUBPATH			L"\\PNotes.chm"
#define	HELP_PDF_SUBPATH		L"\\PNotes.pdf"
#define	SPELL_DIR				L"\\dictionaries\\"
#define	MAIL_SUBJECT			L"Sent from PNotes. Note name: '"
#define	NOTE_CAPTION_FIRST_PART	L"PNotes - ["
#define	OLD_V_OPEN_FILE_FILTER	L"PNotes old versions data base (*.pndb)\0*.pndb\0\0"
#define	LOAD_NOTE_FILTER		L"PNotes files (*.pnote)\0*.pnote\0\0"
#define	FULL_BACKUP_FILTER		L"PNotes full backup files (*.pnfb)\0*.pnfb\0\0"
#define EXECUTABLE_FILTER		L"Executable files (*.exe)\0*.exe\0\0"
#define	TEXT_FILE_FILTER		L"Text Documents (*.txt)\0*.txt\0\0"
#define PROG_PAGE_MENU_ITEM		L"PNotes Homepage"
#define	DEF_PROG_TOOLTIP		L"PNotes - your virtual desktop notes organizer"
#define	DEF_MAIL_SUBJECT		L"Sent from PNotes"
#define	AUTOSAVE_INDEX_FILE		L"~.ni~"
#define	OPEN_PICTURE_FILTER		L"Supported Files Types(*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.ico;*.cur;*.emf;*.wmf)\0*.bmp;*.png;*.gif;*.jpg;*.jpeg;*.ico;*.cur;*.emf;*.wmf\0Bitmaps (*.bmp)\0*.bmp\0PNG Files (*.png)\0*.png\0GIF Files (*.gif)\0*.gif\0JPEG Files (*.jpg, *.jpeg)\0*.jpg\0Icons (*.ico)\0*.ico\0Cursors (*.cur)\0*.cur\0Enhanced Metafiles (*.emf)\0*.emf\0Windows Metafiles (*.wmf)\0*.wmf\0\0";
#define	GROUP_ICONS_FILTER		L"Bitmaps (*.bmp)\0*.bmp\0\0"
#define	N_NOTE_IN_FAVORITES		L"__#$%_no_favorites_&%#__"
#define	SPELL_LIB				L"libhunspell.dll"

//datetime help strings
#define	DATE_FORMAT_MASKS		L"d\tDay of month as digits with no leading zero for single-digit days.\n"\
								"dd\tDay of month as digits with leading zero for single-digit days.\n"\
								"ddd\tDay of week as a three-letter abbreviation.\n"\
								"dddd\tDay of week as its full name.\n"\
								"M\tMonth as digits with no leading zero for single-digit months.\n"\
								"MM\tMonth as digits with leading zero for single-digit months.\n"\
								"MMM\tMonth as a three-letter abbreviation.\n"\
								"MMMM\tMonth as its full name.\n"\
								"y\tYear as last two digits, but with no leading zero for years less than 10.\n"\
								"yy\tYear as last two digits, but with leading zero for years less than 10.\n"\
								"yyyy\tYear represented by full four digits."
#define	TIME_FORMAT_MASKS		L"h\tHours with no leading zero for single-digit hours; 12-hour clock.\n"\
								"hh\tHours with leading zero for single-digit hours; 12-hour clock.\n"\
								"H\tHours with no leading zero for single-digit hours; 24-hour clock.\n"\
								"HH\tHours with leading zero for single-digit hours; 24-hour clock.\n"\
								"m\tMinutes with no leading zero for single-digit minutes.\n"\
								"mm\tMinutes with leading zero for single-digit minutes.\n"\
								"s\tSeconds with no leading zero for single-digit seconds.\n"\
								"ss\tSeconds with leading zero for single-digit seconds.\n"\
								"t\tOne character time-marker string, such as A or P.\n"\
								"tt\tMulticharacter time-marker string, such as AM or PM.\n"
//skin resources
#define	SKN_INFO				L"SKN_INFO"
#define	SKN_MASK				"SKN_MASK"
#define	SKN_VERT_TBR			"SKN_VERT_TBR"

#define	FONT_NP					L"Courier New"

#define	RTF_START				"{\\rtf"
